_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  automated_cron: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_color_modes_toggler: 0
  breakpoint: 0
  ckeditor5: 0
  ckeditor5_max_block_width: 0
  color_field: 0
  config: 0
  config_ignore: 0
  contextual: 0
  crop: 0
  datetime: 0
  dblog: 0
  ddeck_advanced_media: 0
  dynamic_page_cache: 0
  edit_media_modal: 0
  editor: 0
  entity_page_title_manage_display: 0
  entity_stretched_link: 0
  field: 0
  field_formatter_class: 0
  field_group: 0
  field_ui: 0
  file: 0
  filepond: 0
  filter: 0
  focal_point: 0
  help: 0
  helper_class: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  manage_display: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  navigation: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  scheduler: 0
  search: 0
  shortcut: 0
  speculative_loading: 0
  system: 0
  tagify: 0
  tagify_user_list: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  radix: 0
  radix_admin: 0
  ddeck: 0
profile: standard
