_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: b9de2cf3-df77-4635-9c0d-9a8297bcf368
name: DDeck
mail: me@wwwahe.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/5
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
